name: Stuff and things
about: things
body:
- type: markdown
  attributes:
    value: "tell me something"
- type: textarea
  attributes:
    label: "Bugs"
    render: ruby
- type: dropdown
  attributes:
    label: How did you download the software?
    multiple: true
    options:
      - Homebrew
      - MacPorts
      - apt-get
      - Built from source
  validations:
    required: true
- type: checkboxes
  attributes:
    label: What kinds of cats do you like?
    description: You may select more than one.
    options:
      - label: Orange cat (required. Everyone likes orange cats.)
        required: true
      - label: Black cat
