name: Hackathon Submission
description: Fill this out to submit your project
labels: "Hackathon Submission"
body:
- type: input
  attributes:
    label: Project Name
  validations:
    required: true
- type: textarea
  attributes:
    label: Summary of the Project
    description: Feel free to attach screenshots, gifs, etc
  validations:
    required: true
- type: textarea
  attributes:
    label: Who worked on what?
    description: We love when everyone is included
  validations:
    required: true
- type: dropdown
  attributes:
    label: Is this currently in a shipable state?
    options:
      - "yes"
      - "no"
  validations:
    required: true
- type: textarea
  attributes:
    label: If this isn't ready to ship, what would need to be done to get it there?
- type: input
  attributes:
    label: Are there any other teams that should be consulted prior to shipping this?
    description: As a reminder, this is theoretical and not all projects will ship. This is to help us gauge the level of effort needed to get things shipped.
- type: checkbox
  id: cat-preferences
  attributes:
    label: What kinds of cats do you like?
    description: You may select more than one.
    options:
      - label: Orange cat (required. Everyone likes orange cats.)
        required: true
      - label: **Black cat**
