name: Paddington Bear
about: things
body:
- type: markdown
  attributes:
    value: "Paddington Bear is so kind and lovely, prove me wrong"
- type: textarea
  attributes:
    label: "Favorite Paddington moment?"
