name: Weekly Report

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-done-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get cards from done column
        uses: actions/github-script@0.8.0
        with:
          script: |
             const result = await github.projects.listCards({ column_id: 13318641 })
             console.log(result.data)
